### ISSUE TITLE
Cura Configuration Errors

### ISSUE THREAD

**Issue by 1malex** [Nounnours/FlashForge_Creator_3-and-Pro-Cura-profiles#1]
Very new to using custom profiles for Cura (running Cura 5.3), but I copied across all the files into their corresponding folders.
Im working on MacOS, and there are double ups of the folders for 'definition' 'extruder' and 'scripts' in both the MacOS and 
Resources folders inside the Cura contents.
I'm not sure if this method is correct or not. 
Also their is no corresponding folder for 'machine_instances' 
But when I boot Cura after copying these folders I end up with this error:

<img width="391" alt="Screenshot 2023-03-30 at 15 12 29" src="https://user-images.githubusercontent.com/95004879/228728940-f35717f6-1e6d-450d-b745-60bd978c19b8.png">

**Comment by Nounnours** [comment]
Hi,

I'll have a check on Cura 5.3 I did that on Cura 5.2 on Windows 10/11
Hopefully the files are the same on MacOS but I have no way of testing this 

As far as I know it should work since I tried adding this to a clean cura install and it loaded correctly (at least on 5.2.1)

I'll get back here with my results after updating!

**Comment by Nounnours** [comment]
Hey me again, so I updated cura to 5.3 and the profile seem to load perfectly fine (cura just copied it over from 5.2.1) 
still on Windows 11 (64Bits)

Maybe there's something specific to MacOS that is missing in my files?

I'll double check later with a clean install if that changes anything in 5.3 but updating worked for me

**Comment by Nounnours** [comment]
I just thought of 1 thing but these files have been edited under windows maybe the end of line characters are not set the same as MacOS? I didn't check this when making it since it just works for windows

I know that MacOS/Linux uses different end of line characters in general and this causes issues randomly when playing on different OS

That could confuse your OS and make the file appear corrupted?

**Comment by 1malex** [comment]
Thanks for the response,
I will set this up on my PC instead, and give that a test

**Comment by a-hoppz** [comment]
I ignored the error on MacOS and continued with a print and it seems to be working perfectly fine  so must be a perceived issue. 
The only issue I'm encountering is starting the print causes a sizeable blob to form from the extruded while it's heating up which can interrupt the first layer. 
Have you had anything like this or suggest any way to print a purge a line in cues before beginning the actual model?
I've set to print with a brim as a 'purge' line but this can be a bit too close to the first layer and still interpret

**Comment by 1malex** [comment]
I've installed this onto my PC but have encountered the same problem as MacOS.
Just to check I'm installing it correctly, my install is:

Within .../share/cura/resources 
I copy:

'definitions' files -> definitions 
'extruders' files -> extruders 
'quality_changes' files -> quality/flashforge 

Within .../share/cura/plugins/PostProcessingPlugins

'scripts' files -> scripts

The only thing I'm unsure of placement is the 'machine_instances' files

**Comment by Nounnours** [comment]
so all these should pretty much go into the appData/Roaming/cura/5.3 folder
C:/user/{YOUR NAME}/appData/Roaming/cura/5.3/ for the full path
(windows key + r then type appData and hit enter)

Here's how the folder should look with all the folders from the profile + all of Cura things
![image](https://user-images.githubusercontent.com/47520744/229100259-22550687-db65-407a-b923-4218f0d690d1.png)

I'm testing on a clean install just now see how that goes and if I can get the error too 



Edit: I forgot to mention but that's where the machine_instances folder goes too ;)

**Comment by Nounnours** [comment]
Re-reading your comment

Did you install the profile under this folder ?:
C:\Program Files\UltiMaker Cura 5.3.0\share\cura\resources

if so this is not where the profile should go!
And would potentially explain your issues :)

these go into appData folder inside your windows user folder (this is also where cura keeps track of your customised settings etc)
See previous message on how to get there :)

A similar folder must exist in MacOS

but this profile does not go into the installation folder of Cura :)

**Comment by Nounnours** [comment]
Hey update

so I found out that Cura actually can open the config folder for you by going in there:
![image](https://user-images.githubusercontent.com/47520744/229106678-a3191323-db66-4af7-96f3-258d2753e2df.png)


The cool thing is that it should also take you where you need to be on MacOS

I just tried on Windows and it opens the proper appData subfolder :)

Once in there simply paste the profile and it should work fine !
(Note that you may need to reinstall cura to clean up the install folder from any stray files from the profiles causing crash :)

**Comment by 1malex** [comment]
Awesome, that's exactly what I was looking for - where do I actually put the folders 

I've done this on both Mac and Windows and am still getting the same errors which is confusing. 

Although if I ignore them I can still add the creator 3 fan on/off and generate Gcode for a print so i will do some test prints and see if it still works as intended

**Comment by Nounnours** [comment]
Perfect!

I was thinking but maybe putting the profile in the installation folder messed up something in Cura maybe simple reinstall of the software will fix that?
the profile should stay in the config folder too but worst case it's easy to find :)

Good luck with the prints :)

Also quick note on the Chassi fans



Edit: The 2 profiles are Heated chamber and "normal"
The "heated one turns off the chassi fans
The other one turns them ON

But you can also simply edit the start Gcode like you probably did with the chassis fan Command you need :)

**Comment by theRealAJR** [comment]
First of all: Thanks for making this!

I'm afraid I have the same problem as @a-hoppz :
![2023-04-13 Cura Errors](https://user-images.githubusercontent.com/33065735/231833337-20658c38-b519-4579-a876-68b64a8f1c47.png)
It is shown every time Cura is started.
It can be ignored, but Cura crashes when I click on Preferences -> Materials with the error below.

When I reset Cura, then it does not crash any more - I did not try re-installing it yet, but resetting it seems to clear everything out properly.

I was only able to print something once, after that it did not heat up properly any more. That may be related to disabling the left extruder (to avoid that it heats up), but I need to experiment more to figure it out...

Error traceback:
Traceback (most recent call last):
  File "UM\Settings\Models\ContainerPropertyProvider.py", line 84, in setKey
    self._update()
  File "UM\Settings\Models\ContainerPropertyProvider.py", line 148, in _update
    new_properties[property_name] = self._getPropertyValue(property_name)
  File "UM\Settings\Models\ContainerPropertyProvider.py", line 167, in _getPropertyValue
    property_value = SettingDefinition.settingValueToString(setting_type, property_value)
  File "UM\Settings\SettingDefinition.py", line 619, in settingValueToString
    return convert_function(value)
  File "UM\Settings\SettingDefinition.py", line 757, in <lambda>
    "float": {"from": lambda v: str(round(float(v), 4)) if v is not None else "", "to": toFloatConversion, "validator": Validator},
TypeError: float() argument must be a string or a real number, not 'SettingFunction'


Logs:
`Thread 0x0000625c (most recent call first):
  File "C:\Program Files\UltiMaker Cura 5.3.0\share\cura\plugins\USBPrinting\USBPrinterOutputDeviceManager.py", line 90 in _updateThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000067bc (most recent call first):
  File "threading.py", line 324 in wait
  File "zeroconf\__init__.py", line 2534 in wait
  File "zeroconf\__init__.py", line 1715 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x0000591c (most recent call first):
  File "threading.py", line 324 in wait
  File "threading.py", line 600 in wait
  File "C:\Program Files\UltiMaker Cura 5.3.0\share\cura\plugins\UM3NetworkPrinting\src\Network\ZeroConfClient.py", line 81 in _handleOnServiceChangedRequests
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x0000067c (most recent call first):
  File "zeroconf\__init__.py", line 1369 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000057ac (most recent call first):
  File "C:\Program Files\UltiMaker Cura 5.3.0\share\cura\plugins\RemovableDriveOutputDevice\RemovableDrivePlugin.py", line 61 in _updateThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00006a20 (most recent call first):
  File "UM\Backend\Backend.py", line 169 in _storeStderrToLogThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000066b8 (most recent call first):
  File "UM\Backend\Backend.py", line 157 in _storeOutputToLogThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000063cc (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000048b4 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000024b8 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000054d4 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x0000598c (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00002810 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00004110 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00000f18 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00005634 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00002c20 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x0000062c (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000053cc (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000026d0 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x0000289c (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000050cc (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000067d8 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00001f34 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000034e4 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00005ad8 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000007d8 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00005604 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00003e90 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00004aac (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00003820 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00004004 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00003124 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00003484 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00003c08 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000069c4 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00002c7c (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00001374 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000011c0 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Current thread 0x00003700 (most recent call first):
  File "cura\CrashHandler.py", line 397 in _logInfoWidget
  File "cura\CrashHandler.py", line 182 in _createDialog
  File "cura\CrashHandler.py", line 86 in __init__
  File "cura_app.py", line 165 in exceptHook
  File "UM\Qt\QtApplication.py", line 416 in exec
  File "cura\CuraApplication.py", line 898 in run
  File "cura_app.py", line 239 in <module>
`

**Comment by Nounnours** [comment]
Good news I finally could replicate the issue on my machine working on a fix :)

**Comment by Nounnours** [comment]
Big update came around I ran lot of tests and it seems to be fine now :)

One thing I haven't checked yet is you probably have to manually add the script for the temperature to get rid of the ".0" at the end like described in the readme :)

**Comment by theRealAJR** [comment]
The update solved the problems for me - thank you! 🥇

**Comment by theRealAJR** [comment]
Unfortunately it still crashes when entering Preferences -> Materials.
I added a second printer and when switched to that printer Preferences -> Materials works.

I tried to not extract the quality_changes folder into the Cura settings folder, but that did not help.

**Comment by Nounnours** [comment]
Amazing ! 

Oh yea the material thing I had this on Cura on different machines it's getting better with updates though 
But my ender 3 has the same and I don't have any of the Flashforge stuff on that cura install x)

Maybe I can update something to fix that though I'll try have a go when I get some time again but happy to hear it's going good now :)

**Comment by theRealAJR** [comment]
Having a second printer just to edit the materials is OK - one doesn't update the materials too often anyway... ;)

**Comment by theRealAJR** [comment]
I have tried dual a single extrusion and it both worked fine after I adjusted the profile print settings to be a slow as FlashPrint for the first layer and use 110% extrusion for the first layer and I had to extend the decimal removal for the temperature to M140 - I use this now: 
```
search: M(104|140) S(.+)\.0
replace: M\1 S\2
```
I use a FlashForge Creator 3 Pro and for the tests I used the PLA, that came with the printer.

**Comment by Nounnours** [comment]
Good point with the M140 I should update the mini guide with your changes :)
